App/urls.py
from django.conf.urls import url

from App import views

urlpatterns = [
    url(r'^maps/', views.maps, name='maps'),

    url(r'^index/', views.index, name='index'),

    url(r'^news/', views.news, name='news'),

    url(r'^jokers/', views.jokers, name='jokers'),

    url(r'^home/', views.home, name='home'),

    url(r'^getphone/', views.getphone, name='getphone'),

    url(r'^getticket', views.getticket, name='getticket'),

    url(r'^search/', views.search, name='search'),

    url(r'^calc/', views.calc, name='calc'),

    url(r'^addstudents/', views.addstudents, name='addstudents'),

    url(r'deletestudent', views.delete_student, name='deletestudent'),

    url(r'^getstudents/', views.getstudents, name='getstudents'),

    url(r'^getstudentspage/', views.getstudentspage, name='getstudentspage'),

    url(r'^getcode/', views.getcode, name='getcode'),

    url(r'^login/', views.login, name='login'),
]

Two/urls.py
from django.conf.urls import url

from Two import views

urlpatterns = [
    url(r'^getstugrade/', views.get_stu_grade, name='getstugrade'),

    url(r'^getgradestu/', views.get_grade_stu, name='getgradestu'),

    url(r'^addpersons/', views.add_persons, name='addpersons'),

    url(r'^getpersons/', views.get_persons, name='getpersons'),

    url(r'^addperson/', views.add_person, name='addperson'),

    url(r'^getgrades/', views.get_grades, name='getgrades'),

    url(r'^students/(\d+)/', views.students, name='students'),

    url(r'^getanimals/', views.get_animals, name='getanimals'),

    url(r'^getstudents/', views.get_students, name='getstudents'),

    url(r'^addstudent/', views.add_student, name='addstudent'),

    url(r'^delstudent/(?P<id>\d+)', views.del_student, name='delstudent'),

    url(r'^login/', views.login, name='login'),

    url(r'^register/', views.register, name='register'),

    url(r'^mine/', views.mine, name='mine'),

    url(r'^logout/', views.logout, name='logout'),

    url(r'^verifycode/', views.verifyCode, name='verifycode'),

    url(r'^index/', views.index, name='index'),

    url(r'^verifycodeValid/', views.verifycodeValid, name='verifycodeValid'),

    url(r'^upload/', views.upload, name='upload'),
]

djangocache/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app/', include(('App.urls', 'App'), namespace='App')),
    url(r'^two/', include(('Two.urls', 'Two'), namespace='Two')),
    url(r'^user/', include(('user.urls', 'user'), namespace='user')),
]

templates/get_users.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>getusers</title>
</head>
<body>
<h1>getusers</h1>
<hr>
<ul>
    {% for user in users %}
        <li>{{ user.u_name }}</li>
    {% endfor %}

</ul>
</body>
</html>

templates/getpersons.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>getpersons</title>
</head>
<body>
<h1>get person</h1>
<ul>
    {% for person in persons %}
        <li>姓名：{{ person.p_name }} 年龄：{{ person.p_age }}</li>
    {% endfor %}
</ul>
</body>
</html>

templates/getstudentspage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>students2</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
</head>
<body>
<ul>
    {% for student in page_object.object_list %}
        <li>{{ student.s_name }}</li>
    {% endfor %}

</ul>
{#<ul>#}
{#    {% for page_index in page_range %}#}
{#        <li>#}
{#            <a href="{% url 'App:getstudentspage' %}?page={{ page_index }}">{{ page_index }}</a>#}
{#        </li>#}
{#    {% endfor %}#}
{##}
{#</ul>#}
<nav aria-label="Page navigation">
    <ul class="pagination">
        {% if page_object.has_previous %}
            <li>
                <a href="{% url 'App:getstudentspage' %}?page={{ page_object.previous_page_number }}"
                   aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% else %}
            <li class="disabled">
                <a href="#" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% endif %}

        {% for page_index in page_range %}
            <li><a href="{% url 'App:getstudentspage' %}?page={{ page_index }}">{{ page_index }}</a></li>
        {% endfor %}
        {% if page_object.has_next %}
            <li>
                <a href="{% url 'App:getstudentspage' %}?page={{ page_object.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% else %}
            <li class="disabled">
                <a href="#" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% endif %}

    </ul>
</nav>

</body>
</html>

templates/gradelist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>gradelist</title>
</head>
<body>
{#    {% for grade in grades %}#}
{#        <li><a href="/Two/students/{{ grade.id }}">{{ grade.g_name }}</a></li>#}
{#    {% endfor %}#}

    {% for grade in grades %}
        <li><a href="{% url 'Two:students' grade.id %}">{{ grade.g_name }}</a></li>
    {% endfor %}
        <button><a href="{% url 'Two:addstudent' %}">添加</a></button>


</body>
</html>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>verifycode</title>
    <script type="text/javascript" src="{% static 'js/refresh.js' %}" ></script>
</head>
<body>
{#    <img id='verifycode' src="../static/images/" alt="CheckCode"/>#}
    <form method='post' action='{% url 'Two:verifycodeValid' %}'>
        {% csrf_token %}
        <input type="text" name="vc">
        <img id='verifycode' src="/two/verifycode/" alt="CheckCode"/>
    <span id='verifycodeChange'>看不清，换一个</span>
    <br>
    <input type="submit" value="提交">
    </form>

</body>
</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login</title>
    <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/login.css' %}" type="text/css">
    <script type="text/javascript" src="{% static 'js/login.js' %}"></script>
</head>
<body>
<form action="{% url 'App:login' %}" method="post">
    {% csrf_token %}
    用户名：<input type="text" name="username">
    <br>
    <img src="{% url 'App:getcode' %}" alt="验证码">
    <br>
    验证码：<input type="text" name="verifycode">
    <br>
{#    <button>登录</button>#}
    <input type="submit" value="登录" id="submit" onclick="">
</form>
</body>
</html>

templates/map_test.html
<!doctype html>
<html lang="en">
  <head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.1.1/css/ol.css" type="text/css">
    <style>
      .map {
        height: 400px;
        width: 400px;
      }
    </style>
    <script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.1.1/build/ol.js"></script>
    <title>OpenLayers example</title>
  </head>
  <body>
    <h2>My Map</h2>
    <div id="map" class="map"></div>
    <script type="text/javascript">
      var map = new ol.Map({
        target: 'map',
        layers: [
          new ol.layer.Tile({
            source: new ol.source.OSM()
          })
        ],
        view: new ol.View({
          center: ol.proj.fromLonLat([120.21, 30.22]),
          zoom: 11
        })
      });
    </script>
  </body>
</html>

templates/mine.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Mine</title>
</head>
<body>
<h2>欢迎{{ username }}</h2>
<a href="{% url 'Two:logout' %}">退出</a>
</body>
</html>

templates/newslist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>newslist</title>
</head>
<body>
<ul>
    {% for foo in newlist %}
        <li>{{ foo }}</li>
    {% endfor %}
    
</ul>
</body>
</html>

templates/studentlist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>studentlist</title>
</head>
<body>
<ul>
        {% for student in students %}
            <li>{{ student.s_name }}</li>
            <button><a href="{% url 'Two:delstudent' student.id %}">删除</a></button>
        {% endfor %}
</ul>
</body>
</html>

templates/students.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>students</title>
</head>
<body>
<ul>
    {% for student in students %}
        <li>{{ student.s_name }}</li>
    {% endfor %}
</ul>
</body>
</html>

templates/two_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TwoLogin</title>
</head>
<body>
<form action="{% url 'Two:login' %}" method="post">
    {% csrf_token %}
    用户名：<input type="text" name="uname">
    <br>
{#    密码：<input type="text" name="password">#}
    <button>登录</button>
</form>
</body>
</html>

templates/two_register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TwoRegitser</title>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}

</form>
</body>
</html>

templates/upload.html
<html>
<head>
    <title>文件上传</title>
</head>
<body>
    <form method="post" action="{% url 'Two:upload' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="pic"/><br>
        <input type="submit" value="上传">
    </form>
</body>
</html>